language: elixir
elixir:
- 1.3.4
- 1.4.5
- 1.5.2
- 1.6.5
otp_release:
- 18.3
- 19.3
- 20.3
matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.3
  - elixir: 1.4.5
    otp_release: 20.3
  - elixir: 1.6.5
    otp_release: 18.3
  - elixir: 1.6.5
    otp_release: 19.3
env:
- MIX_ENV=test
script:
- mix test --no-start
