language: elixir
elixir:
  - 1.8
  - 1.9
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 20.3

env:
- MIX_ENV=test
script:
- mix test --no-start
